### PR TITLE
rename 'clobber' to 'overwrite' in calls to fits.writeto()

### PR DESCRIPTION
**Pull request by nden**
@mcara

### CODE REVIEW

**Comment by mcara** [comment]
I do not think this PR covers the issue of clobber used in ``headerlet`` (which was my main concern in https://github.com/spacetelescope/stwcs/issues/23). And this is where things get crazy since headerlets are subclasses of ``FitsHDU`` and therefore it _seems_ that if we are switching to ``overwrite`` in calls to ``writeto`` we should also witch to using ``overwrite`` in calls to other headerlet functions such as ``tofile``, ``extract_headerlet``, etc. It would be strange if some functions would take ``clobber`` while others would take ``overwrite``.

**Comment by nden** [comment]
@mcara This certainly covers the deprecation in io.fits without changing the interface in stwcs.
I fail to see why we should change this interface without a reason and especially without any discussions. All function in headerlets take `clobber` and not `overwrite`.  So the change in this PR should be transparent to users.
I may be missing something but I thought the goal is to stop having `DeprecationWarning` messages and *not* to change the current interface.

**Comment by jdavies-st** [comment]
For the JWST package, I made the clobber/overwrite changes as follows:

- Make sure none of our code produces `DeprecationWarning` messages on its own.  So always pass `overwrite` to `io.fits`.  I didn't bother doing an astropy version check as JWST pipeline is tied to new versions of astropy already.
- If a user of our code passes `clobber` as a kwarg, then our code passes it along to `io.fits` so that the user has the chance to see the `DeprecationWarning` from astropy.  I didn't want to hide from the user the fact that the user needed to modify their own scripts or code if it makes use of our code and the astropy code base.

I don't know if this is the correct way forward, but it is what I did.  It means that our interface tracks the astropy interface, at least for JWST.

**Comment by nden** [comment]
@jdavies-st This sounds right to me for jwst. For packages that have been out and may be used in other users's code changing our interface seems unnecessary pain. If that's what we decide to do it should go through its own deprecation period, right?

**Comment by mcara** [comment]
@nden Here is an example of what I was talking about:
```python
>>> from stwcs.wcsutil import headerlet
No TEAL-based tasks available for this package!
>>> h = headerlet.create_headerlet('j8bt06nyq_flt.fits')
>>> h.tofile('headerlet', clobber=True)
WARNING: AstropyDeprecationWarning: "clobber" was deprecated in version 1.3 and will be removed in a future version. Use argument "overwrite" instead. [astropy.utils.decorators]
>>> # If I try to use overwrite instead of clobber to get rid of warnings:
>>> h.tofile('headerlet', overwrite=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: tofile() got an unexpected keyword argument 'overwrite'
```
This error is due to the fact that we overwrite ``tofile`` in our code - see https://github.com/spacetelescope/stwcs/blob/master/stwcs/wcsutil/headerlet.py#L2399. Therefore, it seems to me that it is necessary to implement the same kind of deprecation of ``clobber`` in our code as it was done in astropy. However, if we do this only for ``tofile`` then other functions such as ``extract_headerlet`` (see https://github.com/spacetelescope/stwcs/blob/master/stwcs/wcsutil/headerlet.py#L541) will continue using ``clobber``. Should we also switch all other functions to using ``overwrite`` for consistency?

**Comment by mcara** [comment]
@nden 
> I fail to see why we should change this interface without a reason and _especially without any discussions_.
This is what I was trying to start in https://github.com/spacetelescope/stwcs/issues/23 I will re-post my last message to https://github.com/spacetelescope/stwcs/issues/23 so that the discussion can be continued there.

**Comment by nden** [comment]
@mcara This is exactly the example that this PR fixes. 
When you say `we overwrite tofile() in our code` do you mean drizzlepac?

Headerlet uses HDUList.writeto() in Headerlet.tofile(). 
HDUList.writeto is not exposed directly anywhere.

**Comment by mcara** [comment]
Ah, my bad: ``tofile`` is not inherited from parent class and instead it is our own function. However, ``writeto`` is accessible to the users.

``tofile`` essentially is a copy of ``writeto`` (with some verification) and it uses ``writeto``. Shouldn't we surround the call to ``writeto()`` (see https://github.com/spacetelescope/stwcs/blob/master/stwcs/wcsutil/headerlet.py#L2416) with the same ```if ASTROPY_13_MIN: ... else: ...```?

**Comment by mcara** [comment]
I hate the lull in activity here 😄 Is there a consensus on this subject? Is, at the very least, a feeling that this PR is acceptable?

**Comment by mcara** [comment]
I think this is OK to merge.

**Comment by nden** [comment]
Yah. Travis reports failures although all builds and tests finished with status 0.

**Pull request merged**
