### PR TITLE
suppress warning messages when it's known they are not relevant

### LINKED ISSUE #25: Remove SIP from headers when loading alternative WCS
Drizzlepac logs often contain numerous messages about inconsistent use of SIP in HST images, see, e.g., https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=40222839 such as:
```
INFO: 
                Inconsistent SIP distortion information is present in the FITS header and the WCS object:
                SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
                astropy.wcs is using the SIP distortion coefficients,
                therefore the coordinates calculated here might be incorrect.

                If you do not want to apply the SIP distortion coefficients,
                please remove the SIP coefficients from the FITS header or the
                WCS object.  As an example, if the image is already distortion-corrected
                (e.g., drizzled) then distortion components should not apply and the SIP
                coefficients should be removed.

                While the SIP distortion coefficients are being applied here, if that was indeed the intent,
                for consistency please append "-SIP" to the CTYPE in the FITS header or the WCS object.

                 [astropy.wcs.wcs]
```
Often this happens when ``drizzlepac`` code attempts to load the "original" WCS (the one that relies on ``IDCTAB`` instead of ``SIP`` to describe distortions). ``stwcs`` should be modified to remove SIP from image headers before loading alternative WCS.

### PR DESCRIPTION
**Pull request by nden**
This closes #25 #26 but takes a different approach. The warnings are filtered out. It's safe to do this because only one specific warning is filtered out and only in cases when it's not relevant.

### CODE REVIEW

**Comment by nden** [comment]
Merging so drizzlepac tests can run tonight.

**Comment by mcara** [comment]
This did not solve the issue: search for "Inconsistent SIP distortion information" in https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&qid=1353

**Comment by nden** [comment]
It's possible I missed a case, that's why I want to check the test results. Unfortunately I didn't merge in time for the build last night and need to wait for the next round of tests (the one that starts at 10:30 am).

**Comment by mcara** [comment]
Unfortunately, it seems that the messages are still issued in all STIS tests: https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&qid=2473

CC: @nden, @stsci-hack

**Pull request merged**
